# esysusers
# Autogenerated from man page /usr/share/man/man8/esysusers.8.gz
complete -c esysusers -l root -d 'Takes a directory path as an argument'
complete -c esysusers -l image -d 'Takes a path to a disk image file or block device node'
complete -c esysusers -l image-policy -d 'Takes an image policy string as argument, as per systemd. image-policy(7)'
complete -c esysusers -l dry-run -d 'Process the configuration and figure out what entries would be created, but d…'
complete -c esysusers -l inline -d 'Treat each positional argument as a separate configuration line instead of a …'
complete -c esysusers -l cat-config -d 'Copy the contents of config files to standard output'
complete -c esysusers -l tldr -d 'Copy the contents of config files to standard output'
complete -c esysusers -l no-pager -d 'Do not pipe output into a pager'
complete -c esysusers -s h -l help -d 'Print a short help text and exit'
complete -c esysusers -l version -d 'Print a short version string and exit'
complete -c esysusers -l replace -d 'is specified, arguments specified on the command line are used instead of the…'

