# etmpfiles
# Autogenerated from man page /usr/share/man/man8/etmpfiles.8.gz
complete -c etmpfiles -l create
complete -c etmpfiles -l remove
complete -c etmpfiles -l clean
complete -c etmpfiles -l replace -d 'is specified, arguments specified on the command line are used instead of the…'
complete -c etmpfiles -l purge
complete -c etmpfiles -l dry-run -d '(see below) to verify which files and directories will be deleted'
complete -c etmpfiles -l user
complete -c etmpfiles -l boot
complete -c etmpfiles -l graceful
complete -c etmpfiles -l prefix
complete -c etmpfiles -l exclude-prefix
complete -c etmpfiles -s E
complete -c etmpfiles -l root
complete -c etmpfiles -l image
complete -c etmpfiles -l image-policy
complete -c etmpfiles -l cat-config
complete -c etmpfiles -l tldr
complete -c etmpfiles -l no-pager
complete -c etmpfiles -s h -l help
complete -c etmpfiles -l version

